export const adress = 'http://localhost:3001/'
export const loginEndPoint = adress + "users/login"
export const singUpEndPoint = adress + 'users/createUser'
export const getAllPostsEndPoint= adress+'posts/getTopPosts'
export const getAllTopPostsEndPoint=adress+'posts/getTopLiked'
export const createPostendPoint=adress+'posts/createPost'
export const getTypesOfPostendPoint=adress+'posts/getTypesOfPost'
export const getCommentsendPOint=adress+'comments/getPostComments'
export const createCommentendPoint=adress+'comments/createComment'
export const getUsersPostsendPoint=adress+"posts/getPostsByUser"
export const getLogedUserendPoint=adress+"user/getLogedUser"
export const getPostByTitleendpoint=adress+"posts/getPost"
export const likePostEndPoint=adress+"users/likePost" 
export const editPostEndPoint=adress+"posts/editPost"
export const didUserLikeEndPoint=adress+"posts/isPostLiked"
export const dislikePost=adress+"users/dislikePost"
export const getUserFromPost=adress+"posts/getUserFromPost"
export const deletePostEndPoint=adress+"posts/deletePost"
export const checkIfUserIsLogedEndPoint=adress+"users/getLogedUser"
export const logOutUserEndPoint=adress+"users/logoutUser"